export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_SURF_ACCOUNT_DETAILS = 'GET_SURF_ACCOUNT_DETAILS';
export const PUT_SURF_ACCOUNT_DETAILS = 'PUT_SURF_ACCOUNT_DETAILS';
export const PUT_PROFILE_PIC = 'PUT_PROFILE_PIC';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';